extends Panel


@onready var timer = get_node("%time")
@onready var important_vars = $"%impvars"
@onready var booking_screen = $"%BookingScreen"
@onready var lesson_grid = $"%LessonGrid"
@onready var button_grid = $"%ButtonGrid"
@onready var reset_menu = $"%ResetMenu"
@onready var password_field = $"%PasswordField"


func _on_ResetButton_pressed():
	if password_field.text == "Heather":
		get_tree().reload_current_scene()

func _on_CancelReset_pressed():
	reset_menu.visible = false
	lesson_grid.visible = true
	button_grid.visible = true
