extends Node


var pod
var time
var day_uid
var day_uid2

var current_pod : String

var a1l1_booked : bool
var a2l1_booked : bool
var b1l1_booked : bool
var b2l1_booked : bool
var cl1_booked : bool
var dl1_booked : bool
var el1_booked : bool
var fl1_booked : bool
var gl1_booked : bool

var a1l2_booked : bool
var a2l2_booked : bool
var b1l2_booked : bool
var b2l2_booked : bool
var cl2_booked : bool
var dl2_booked : bool
var el2_booked : bool
var fl2_booked : bool
var gl2_booked : bool

var a1l3_booked : bool
var a2l3_booked : bool
var b1l3_booked : bool
var b2l3_booked : bool
var cl3_booked : bool
var dl3_booked : bool
var el3_booked : bool
var fl3_booked : bool
var gl3_booked : bool

var a1l4_booked : bool
var a2l4_booked : bool
var b1l4_booked : bool
var b2l4_booked : bool
var cl4_booked : bool
var dl4_booked : bool
var el4_booked : bool
var fl4_booked : bool
var gl4_booked : bool

var a1l5_booked : bool
var a2l5_booked : bool
var b1l5_booked : bool
var b2l5_booked : bool
var cl5_booked : bool
var dl5_booked : bool
var el5_booked : bool
var fl5_booked : bool
var gl5_booked : bool

var a1l6_booked : bool
var a2l6_booked : bool
var b1l6_booked : bool
var b2l6_booked : bool
var cl6_booked : bool
var dl6_booked : bool
var el6_booked : bool
var fl6_booked : bool
var gl6_booked : bool

var a1l7_booked : bool
var a2l7_booked : bool
var b1l7_booked : bool
var b2l7_booked : bool
var cl7_booked : bool
var dl7_booked : bool
var el7_booked : bool
var fl7_booked : bool
var gl7_booked : bool

var a1l8_booked : bool
var a2l8_booked : bool
var b1l8_booked : bool
var b2l8_booked : bool
var cl8_booked : bool
var dl8_booked : bool
var el8_booked : bool
var fl8_booked : bool
var gl8_booked : bool

# Called when the node enters the scene tree for the first time.
func _ready():
	pass


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
