extends Node

@onready var important_vars = $"%impvars"

@onready var name1 = $"%Name1"
@onready var name2 = $"%Name2"
@onready var form1 = $"%Form1"
@onready var form2 = $"%Form2"
@onready var name3 = $"%Name3"
@onready var form3 = $"%Form3"
@onready var name4 = $"%Name4"
@onready var form4 = $"%Form4"
@onready var reason = $"%ReasonField"

# A1

@export var A1L1_name1 : String
@export var A1L1_name2 : String
@export var A1L1_form1 : String
@export var A1L1_form2 : String
@export var A1L1_reason : String

@export var A1L2_name1 : String
@export var A1L2_name2 : String
@export var A1L2_form1 : String
@export var A1L2_form2 : String
@export var A1L2_reason : String

@export var A1L3_name1 : String
@export var A1L3_name2 : String
@export var A1L3_form1 : String
@export var A1L3_form2 : String
@export var A1L3_reason : String

@export var A1L4_name1 : String
@export var A1L4_name2 : String
@export var A1L4_form1 : String
@export var A1L4_form2 : String
@export var A1L4_reason : String

@export var A1L5_name1 : String
@export var A1L5_name2 : String
@export var A1L5_form1 : String
@export var A1L5_form2 : String
@export var A1L5_reason : String

@export var A1L6_name1 : String
@export var A1L6_name2 : String
@export var A1L6_form1 : String
@export var A1L6_form2 : String
@export var A1L6_reason : String

@export var A1L7_name1 : String
@export var A1L7_name2 : String
@export var A1L7_form1 : String
@export var A1L7_form2 : String
@export var A1L7_reason : String

@export var A1L8_name1 : String
@export var A1L8_name2 : String
@export var A1L8_form1 : String
@export var A1L8_form2 : String
@export var A1L8_reason : String

# A2

@export var A2L1_name1 : String
@export var A2L1_name2 : String
@export var A2L1_form1 : String
@export var A2L1_form2 : String
@export var A2L1_reason : String

@export var A2L2_name1 : String
@export var A2L2_name2 : String
@export var A2L2_form1 : String
@export var A2L2_form2 : String
@export var A2L2_reason : String

@export var A2L3_name1 : String
@export var A2L3_name2 : String
@export var A2L3_form1 : String
@export var A2L3_form2 : String
@export var A2L3_reason : String

@export var A2L4_name1 : String
@export var A2L4_name2 : String
@export var A2L4_form1 : String
@export var A2L4_form2 : String
@export var A2L4_reason : String

@export var A2L5_name1 : String
@export var A2L5_name2 : String
@export var A2L5_form1 : String
@export var A2L5_form2 : String
@export var A2L5_reason : String

@export var A2L6_name1 : String
@export var A2L6_name2 : String
@export var A2L6_form1 : String
@export var A2L6_form2 : String
@export var A2L6_reason : String

@export var A2L7_name1 : String
@export var A2L7_name2 : String
@export var A2L7_form1 : String
@export var A2L7_form2 : String
@export var A2L7_reason : String

@export var A2L8_name1 : String
@export var A2L8_name2 : String
@export var A2L8_form1 : String
@export var A2L8_form2 : String
@export var A2L8_reason : String

# B1

@export var B1L1_name1 : String
@export var B1L1_name2 : String
@export var B1L1_form1 : String
@export var B1L1_form2 : String
@export var B1L1_reason : String

@export var B1L2_name1 : String
@export var B1L2_name2 : String
@export var B1L2_form1 : String
@export var B1L2_form2 : String
@export var B1L2_reason : String

@export var B1L3_name1 : String
@export var B1L3_name2 : String
@export var B1L3_form1 : String
@export var B1L3_form2 : String
@export var B1L3_reason : String

@export var B1L4_name1 : String
@export var B1L4_name2 : String
@export var B1L4_form1 : String
@export var B1L4_form2 : String
@export var B1L4_reason : String

@export var B1L5_name1 : String
@export var B1L5_name2 : String
@export var B1L5_form1 : String
@export var B1L5_form2 : String
@export var B1L5_reason : String

@export var B1L6_name1 : String
@export var B1L6_name2 : String
@export var B1L6_form1 : String
@export var B1L6_form2 : String
@export var B1L6_reason : String

@export var B1L7_name1 : String
@export var B1L7_name2 : String
@export var B1L7_form1 : String
@export var B1L7_form2 : String
@export var B1L7_reason : String

@export var B1L8_name1 : String
@export var B1L8_name2 : String
@export var B1L8_form1 : String
@export var B1L8_form2 : String
@export var B1L8_reason : String

# B2

@export var B2L1_name1 : String
@export var B2L1_name2 : String
@export var B2L1_form1 : String
@export var B2L1_form2 : String
@export var B2L1_reason : String

@export var B2L2_name1 : String
@export var B2L2_name2 : String
@export var B2L2_form1 : String
@export var B2L2_form2 : String
@export var B2L2_reason : String

@export var B2L3_name1 : String
@export var B2L3_name2 : String
@export var B2L3_form1 : String
@export var B2L3_form2 : String
@export var B2L3_reason : String

@export var B2L4_name1 : String
@export var B2L4_name2 : String
@export var B2L4_form1 : String
@export var B2L4_form2 : String
@export var B2L4_reason : String

@export var B2L5_name1 : String
@export var B2L5_name2 : String
@export var B2L5_form1 : String
@export var B2L5_form2 : String
@export var B2L5_reason : String

@export var B2L6_name1 : String
@export var B2L6_name2 : String
@export var B2L6_form1 : String
@export var B2L6_form2 : String
@export var B2L6_reason : String

@export var B2L7_name1 : String
@export var B2L7_name2 : String
@export var B2L7_form1 : String
@export var B2L7_form2 : String
@export var B2L7_reason : String

@export var B2L8_name1 : String
@export var B2L8_name2 : String
@export var B2L8_form1 : String
@export var B2L8_form2 : String
@export var B2L8_reason : String

# C

@export var CL1_name1 : String
@export var CL1_name2 : String
@export var CL1_form1 : String
@export var CL1_form2 : String
@export var CL1_name3 : String
@export var CL1_name4 : String
@export var CL1_form3 : String
@export var CL1_form4 : String
@export var CL1_reason : String

@export var CL2_name1 : String
@export var CL2_name2 : String
@export var CL2_form1 : String
@export var CL2_form2 : String
@export var CL2_name3 : String
@export var CL2_name4 : String
@export var CL2_form3 : String
@export var CL2_form4 : String
@export var CL2_reason : String

@export var CL3_name1 : String
@export var CL3_name2 : String
@export var CL3_form1 : String
@export var CL3_form2 : String
@export var CL3_name3 : String
@export var CL3_name4 : String
@export var CL3_form3 : String
@export var CL3_form4 : String
@export var CL3_reason : String

@export var CL4_name1 : String
@export var CL4_name2 : String
@export var CL4_form1 : String
@export var CL4_form2 : String
@export var CL4_name3 : String
@export var CL4_name4 : String
@export var CL4_form3 : String
@export var CL4_form4 : String
@export var CL4_reason : String

@export var CL5_name1 : String
@export var CL5_name2 : String
@export var CL5_form1 : String
@export var CL5_form2 : String
@export var CL5_name3 : String
@export var CL5_name4 : String
@export var CL5_form3 : String
@export var CL5_form4 : String
@export var CL5_reason : String

@export var CL6_name1 : String
@export var CL6_name2 : String
@export var CL6_form1 : String
@export var CL6_form2 : String
@export var CL6_name3 : String
@export var CL6_name4 : String
@export var CL6_form3 : String
@export var CL6_form4 : String
@export var CL6_reason : String

@export var CL7_name1 : String
@export var CL7_name2 : String
@export var CL7_form1 : String
@export var CL7_form2 : String
@export var CL7_name3 : String
@export var CL7_name4 : String
@export var CL7_form3 : String
@export var CL7_form4 : String
@export var CL7_reason : String

@export var CL8_name1 : String
@export var CL8_name2 : String
@export var CL8_form1 : String
@export var CL8_form2 : String
@export var CL8_name3 : String
@export var CL8_name4 : String
@export var CL8_form3 : String
@export var CL8_form4 : String
@export var CL8_reason : String

# D

@export var DL1_name1 : String
@export var DL1_name2 : String
@export var DL1_form1 : String
@export var DL1_form2 : String
@export var DL1_name3 : String
@export var DL1_name4 : String
@export var DL1_form3 : String
@export var DL1_form4 : String
@export var DL1_reason : String

@export var DL2_name1 : String
@export var DL2_name2 : String
@export var DL2_form1 : String
@export var DL2_form2 : String
@export var DL2_name3 : String
@export var DL2_name4 : String
@export var DL2_form3 : String
@export var DL2_form4 : String
@export var DL2_reason : String

@export var DL3_name1 : String
@export var DL3_name2 : String
@export var DL3_form1 : String
@export var DL3_form2 : String
@export var DL3_name3 : String
@export var DL3_name4 : String
@export var DL3_form3 : String
@export var DL3_form4 : String
@export var DL3_reason : String

@export var DL4_name1 : String
@export var DL4_name2 : String
@export var DL4_form1 : String
@export var DL4_form2 : String
@export var DL4_name3 : String
@export var DL4_name4 : String
@export var DL4_form3 : String
@export var DL4_form4 : String
@export var DL4_reason : String

@export var DL5_name1 : String
@export var DL5_name2 : String
@export var DL5_form1 : String
@export var DL5_form2 : String
@export var DL5_name3 : String
@export var DL5_name4 : String
@export var DL5_form3 : String
@export var DL5_form4 : String
@export var DL5_reason : String

@export var DL6_name1 : String
@export var DL6_name2 : String
@export var DL6_form1 : String
@export var DL6_form2 : String
@export var DL6_name3 : String
@export var DL6_name4 : String
@export var DL6_form3 : String
@export var DL6_form4 : String
@export var DL6_reason : String

@export var DL7_name1 : String
@export var DL7_name2 : String
@export var DL7_form1 : String
@export var DL7_form2 : String
@export var DL7_name3 : String
@export var DL7_name4 : String
@export var DL7_form3 : String
@export var DL7_form4 : String
@export var DL7_reason : String

@export var DL8_name1 : String
@export var DL8_name2 : String
@export var DL8_form1 : String
@export var DL8_form2 : String
@export var DL8_name3 : String
@export var DL8_name4 : String
@export var DL8_form3 : String
@export var DL8_form4 : String
@export var DL8_reason : String

# E

@export var EL1_name1 : String
@export var EL1_name2 : String
@export var EL1_form1 : String
@export var EL1_form2 : String
@export var EL1_name3 : String
@export var EL1_name4 : String
@export var EL1_form3 : String
@export var EL1_form4 : String
@export var EL1_reason : String

@export var EL2_name1 : String
@export var EL2_name2 : String
@export var EL2_form1 : String
@export var EL2_form2 : String
@export var EL2_name3 : String
@export var EL2_name4 : String
@export var EL2_form3 : String
@export var EL2_form4 : String
@export var EL2_reason : String

@export var EL3_name1 : String
@export var EL3_name2 : String
@export var EL3_form1 : String
@export var EL3_form2 : String
@export var EL3_name3 : String
@export var EL3_name4 : String
@export var EL3_form3 : String
@export var EL3_form4 : String
@export var EL3_reason : String

@export var EL4_name1 : String
@export var EL4_name2 : String
@export var EL4_form1 : String
@export var EL4_form2 : String
@export var EL4_name3 : String
@export var EL4_name4 : String
@export var EL4_form3 : String
@export var EL4_form4 : String
@export var EL4_reason : String

@export var EL5_name1 : String
@export var EL5_name2 : String
@export var EL5_form1 : String
@export var EL5_form2 : String
@export var EL5_name3 : String
@export var EL5_name4 : String
@export var EL5_form3 : String
@export var EL5_form4 : String
@export var EL5_reason : String

@export var EL6_name1 : String
@export var EL6_name2 : String
@export var EL6_form1 : String
@export var EL6_form2 : String
@export var EL6_name3 : String
@export var EL6_name4 : String
@export var EL6_form3 : String
@export var EL6_form4 : String
@export var EL6_reason : String

@export var EL7_name1 : String
@export var EL7_name2 : String
@export var EL7_form1 : String
@export var EL7_form2 : String
@export var EL7_name3 : String
@export var EL7_name4 : String
@export var EL7_form3 : String
@export var EL7_form4 : String
@export var EL7_reason : String

@export var EL8_name1 : String
@export var EL8_name2 : String
@export var EL8_form1 : String
@export var EL8_form2 : String
@export var EL8_name3 : String
@export var EL8_name4 : String
@export var EL8_form3 : String
@export var EL8_form4 : String
@export var EL8_reason : String

# F

@export var FL1_name1 : String
@export var FL1_name2 : String
@export var FL1_form1 : String
@export var FL1_form2 : String
@export var FL1_name3 : String
@export var FL1_name4 : String
@export var FL1_form3 : String
@export var FL1_form4 : String
@export var FL1_reason : String

@export var FL2_name1 : String
@export var FL2_name2 : String
@export var FL2_form1 : String
@export var FL2_form2 : String
@export var FL2_name3 : String
@export var FL2_name4 : String
@export var FL2_form3 : String
@export var FL2_form4 : String
@export var FL2_reason : String

@export var FL3_name1 : String
@export var FL3_name2 : String
@export var FL3_form1 : String
@export var FL3_form2 : String
@export var FL3_name3 : String
@export var FL3_name4 : String
@export var FL3_form3 : String
@export var FL3_form4 : String
@export var FL3_reason : String

@export var FL4_name1 : String
@export var FL4_name2 : String
@export var FL4_form1 : String
@export var FL4_form2 : String
@export var FL4_name3 : String
@export var FL4_name4 : String
@export var FL4_form3 : String
@export var FL4_form4 : String
@export var FL4_reason : String

@export var FL5_name1 : String
@export var FL5_name2 : String
@export var FL5_form1 : String
@export var FL5_form2 : String
@export var FL5_name3 : String
@export var FL5_name4 : String
@export var FL5_form3 : String
@export var FL5_form4 : String
@export var FL5_reason : String

@export var FL6_name1 : String
@export var FL6_name2 : String
@export var FL6_form1 : String
@export var FL6_form2 : String
@export var FL6_name3 : String
@export var FL6_name4 : String
@export var FL6_form3 : String
@export var FL6_form4 : String
@export var FL6_reason : String

@export var FL7_name1 : String
@export var FL7_name2 : String
@export var FL7_form1 : String
@export var FL7_form2 : String
@export var FL7_name3 : String
@export var FL7_name4 : String
@export var FL7_form3 : String
@export var FL7_form4 : String
@export var FL7_reason : String

@export var FL8_name1 : String
@export var FL8_name2 : String
@export var FL8_form1 : String
@export var FL8_form2 : String
@export var FL8_name3 : String
@export var FL8_name4 : String
@export var FL8_form3 : String
@export var FL8_form4 : String
@export var FL8_reason : String

# G

@export var GL1_name1 : String
@export var GL1_name2 : String
@export var GL1_form1 : String
@export var GL1_form2 : String
@export var GL1_name3 : String
@export var GL1_name4 : String
@export var GL1_form3 : String
@export var GL1_form4 : String
@export var GL1_reason : String

@export var GL2_name1 : String
@export var GL2_name2 : String
@export var GL2_form1 : String
@export var GL2_form2 : String
@export var GL2_name3 : String
@export var GL2_name4 : String
@export var GL2_form3 : String
@export var GL2_form4 : String
@export var GL2_reason : String

@export var GL3_name1 : String
@export var GL3_name2 : String
@export var GL3_form1 : String
@export var GL3_form2 : String
@export var GL3_name3 : String
@export var GL3_name4 : String
@export var GL3_form3 : String
@export var GL3_form4 : String
@export var GL3_reason : String

@export var GL4_name1 : String
@export var GL4_name2 : String
@export var GL4_form1 : String
@export var GL4_form2 : String
@export var GL4_name3 : String
@export var GL4_name4 : String
@export var GL4_form3 : String
@export var GL4_form4 : String
@export var GL4_reason : String

@export var GL5_name1 : String
@export var GL5_name2 : String
@export var GL5_form1 : String
@export var GL5_form2 : String
@export var GL5_name3 : String
@export var GL5_name4 : String
@export var GL5_form3 : String
@export var GL5_form4 : String
@export var GL5_reason : String

@export var GL6_name1 : String
@export var GL6_name2 : String
@export var GL6_form1 : String
@export var GL6_form2 : String
@export var GL6_name3 : String
@export var GL6_name4 : String
@export var GL6_form3 : String
@export var GL6_form4 : String
@export var GL6_reason : String

@export var GL7_name1 : String
@export var GL7_name2 : String
@export var GL7_form1 : String
@export var GL7_form2 : String
@export var GL7_name3 : String
@export var GL7_name4 : String
@export var GL7_form3 : String
@export var GL7_form4 : String
@export var GL7_reason : String

@export var GL8_name1 : String
@export var GL8_name2 : String
@export var GL8_form1 : String
@export var GL8_form2 : String
@export var GL8_name3 : String
@export var GL8_name4 : String
@export var GL8_form3 : String
@export var GL8_form4 : String
@export var GL8_reason : String

func read_values():
	if important_vars.current_pod == "A1L1":
		name1.text = A1L1_name1
		name2.text = A1L1_name2
		form1.text = A1L1_form1
		form2.text = A1L1_form2
		reason.text = A1L1_reason

	if important_vars.current_pod == "A1L2":
		name1.text = A1L2_name1
		name2.text = A1L2_name2
		form1.text = A1L2_form1
		form2.text = A1L2_form2
		reason.text = A1L2_reason

	if important_vars.current_pod == "A1L3":
		name1.text = A1L3_name1
		name2.text = A1L3_name2
		form1.text = A1L3_form1
		form2.text = A1L3_form2
		reason.text = A1L3_reason

	if important_vars.current_pod == "A1L4":
		name1.text = A1L4_name1
		name2.text = A1L4_name2
		form1.text = A1L4_form1
		form2.text = A1L4_form2
		reason.text = A1L4_reason

	if important_vars.current_pod == "A1L5":
		name1.text = A1L5_name1
		name2.text = A1L5_name2
		form1.text = A1L5_form1
		form2.text = A1L5_form2
		reason.text = A1L5_reason

	if important_vars.current_pod == "A1L6":
		name1.text = A1L6_name1
		name2.text = A1L6_name2
		form1.text = A1L6_form1
		form2.text = A1L6_form2
		reason.text = A1L6_reason
		
	if important_vars.current_pod == "A1L7":
		name1.text = A1L7_name1
		name2.text = A1L7_name2
		form1.text = A1L7_form1
		form2.text = A1L7_form2
		reason.text = A1L7_reason
		
	if important_vars.current_pod == "A1L8":
		name1.text = A1L8_name1
		name2.text = A1L8_name2
		form1.text = A1L8_form1
		form2.text = A1L8_form2
		reason.text = A1L8_reason

# A2

	if important_vars.current_pod == "A2L1":
		name1.text = A2L1_name1
		name2.text = A2L1_name2
		form1.text = A2L1_form1
		form2.text = A2L1_form2
		reason.text = A2L1_reason

	if important_vars.current_pod == "A2L2":
		name1.text = A2L2_name1
		name2.text = A2L2_name2
		form1.text = A2L2_form1
		form2.text = A2L2_form2
		reason.text = A2L2_reason

	if important_vars.current_pod == "A2L3":
		name1.text = A2L3_name1
		name2.text = A2L3_name2
		form1.text = A2L3_form1
		form2.text = A2L3_form2
		reason.text = A2L3_reason

	if important_vars.current_pod == "A2L4":
		name1.text = A2L4_name1
		name2.text = A2L4_name2
		form1.text = A2L4_form1
		form2.text = A2L4_form2
		reason.text = A2L4_reason

	if important_vars.current_pod == "A2L5":
		name1.text = A2L5_name1
		name2.text = A2L5_name2
		form1.text = A2L5_form1
		form2.text = A2L5_form2
		reason.text = A2L5_reason

	if important_vars.current_pod == "A2L6":
		name1.text = A2L6_name1
		name2.text = A2L6_name2
		form1.text = A2L6_form1
		form2.text = A2L6_form2
		reason.text = A2L6_reason
		
	if important_vars.current_pod == "A2L7":
		name1.text = A2L7_name1
		name2.text = A2L7_name2
		form1.text = A2L7_form1
		form2.text = A2L7_form2
		reason.text = A2L7_reason
		
	if important_vars.current_pod == "A2L8":
		name1.text = A2L8_name1
		name2.text = A2L8_name2
		form1.text = A2L8_form1
		form2.text = A2L8_form2
		reason.text = A2L8_reason

	if important_vars.current_pod == "B1L1":
		name1.text = B1L1_name1
		name2.text = B1L1_name2
		form1.text = B1L1_form1
		form2.text = B1L1_form2
		reason.text = B1L1_reason

	if important_vars.current_pod == "B1L2":
		name1.text = B1L2_name1
		name2.text = B1L2_name2
		form1.text = B1L2_form1
		form2.text = B1L2_form2
		reason.text = B1L2_reason

	if important_vars.current_pod == "B1L3":
		name1.text = B1L3_name1
		name2.text = B1L3_name2
		form1.text = B1L3_form1
		form2.text = B1L3_form2
		reason.text = B1L3_reason

	if important_vars.current_pod == "B1L4":
		name1.text = B1L4_name1
		name2.text = B1L4_name2
		form1.text = B1L4_form1
		form2.text = B1L4_form2
		reason.text = B1L4_reason

	if important_vars.current_pod == "B1L5":
		name1.text = B1L5_name1
		name2.text = B1L5_name2
		form1.text = B1L5_form1
		form2.text = B1L5_form2
		reason.text = B1L5_reason

	if important_vars.current_pod == "B1L6":
		name1.text = B1L6_name1
		name2.text = B1L6_name2
		form1.text = B1L6_form1
		form2.text = B1L6_form2
		reason.text = B1L6_reason
		
	if important_vars.current_pod == "B1L7":
		name1.text = B1L7_name1
		name2.text = B1L7_name2
		form1.text = B1L7_form1
		form2.text = B1L7_form2
		reason.text = B1L7_reason
		
	if important_vars.current_pod == "B1L8":
		name1.text = B1L8_name1
		name2.text = B1L8_name2
		form1.text = B1L8_form1
		form2.text = B1L8_form2
		reason.text = B1L8_reason

# B2

	if important_vars.current_pod == "B2L1":
		name1.text = B2L1_name1
		name2.text = B2L1_name2
		form1.text = B2L1_form1
		form2.text = B2L1_form2
		reason.text = B2L1_reason

	if important_vars.current_pod == "B2L2":
		name1.text = B2L2_name1
		name2.text = B2L2_name2
		form1.text = B2L2_form1
		form2.text = B2L2_form2
		reason.text = B2L2_reason

	if important_vars.current_pod == "B2L3":
		name1.text = B2L3_name1
		name2.text = B2L3_name2
		form1.text = B2L3_form1
		form2.text = B2L3_form2
		reason.text = B2L3_reason

	if important_vars.current_pod == "B2L4":
		name1.text = B2L4_name1
		name2.text = B2L4_name2
		form1.text = B2L4_form1
		form2.text = B2L4_form2
		reason.text = B2L4_reason

	if important_vars.current_pod == "B2L5":
		name1.text = B2L5_name1
		name2.text = B2L5_name2
		form1.text = B2L5_form1
		form2.text = B2L5_form2
		reason.text = B2L5_reason

	if important_vars.current_pod == "B2L6":
		name1.text = B2L6_name1
		name2.text = B2L6_name2
		form1.text = B2L6_form1
		form2.text = B2L6_form2
		reason.text = B2L6_reason
		
	if important_vars.current_pod == "B2L7":
		name1.text = B2L7_name1
		name2.text = B2L7_name2
		form1.text = B2L7_form1
		form2.text = B2L7_form2
		reason.text = B2L7_reason
		
	if important_vars.current_pod == "B2L8":
		name1.text = B2L8_name1
		name2.text = B2L8_name2
		form1.text = B2L8_form1
		form2.text = B2L8_form2
		reason.text = B2L8_reason

# C

	if important_vars.current_pod == "CL1":
		name1.text = CL1_name1
		name2.text = CL1_name2
		form1.text = CL1_form1
		form2.text = CL1_form2
		name3.text = CL1_name3
		name4.text = CL1_name4
		form3.text = CL1_form3
		form4.text = CL1_form4
		reason.text = CL1_reason

	if important_vars.current_pod == "CL2":
		name1.text = CL2_name1
		name2.text = CL2_name2
		form1.text = CL2_form1
		form2.text = CL2_form2
		name3.text = CL2_name3
		name4.text = CL2_name4
		form3.text = CL2_form3
		form4.text = CL2_form4
		reason.text = CL2_reason

	if important_vars.current_pod == "CL3":
		name1.text = CL3_name1
		name2.text = CL3_name2
		form1.text = CL3_form1
		form2.text = CL3_form2
		name3.text = CL3_name3
		name4.text = CL3_name4
		form3.text = CL3_form3
		form4.text = CL3_form4
		reason.text = CL3_reason

	if important_vars.current_pod == "CL4":
		name1.text = CL4_name1
		name2.text = CL4_name2
		form1.text = CL4_form1
		form2.text = CL4_form2
		name3.text = CL4_name3
		name4.text = CL4_name4
		form3.text = CL4_form3
		form4.text = CL4_form4
		reason.text = CL4_reason

	if important_vars.current_pod == "CL5":
		name1.text = CL5_name1
		name2.text = CL5_name2
		form1.text = CL5_form1
		form2.text = CL5_form2
		name3.text = CL5_name3
		name4.text = CL5_name4
		form3.text = CL5_form3
		form4.text = CL5_form4
		reason.text = CL5_reason

	if important_vars.current_pod == "CL6":
		name1.text = CL6_name1
		name2.text = CL6_name2
		form1.text = CL6_form1
		form2.text = CL6_form2
		name3.text = CL6_name3
		name4.text = CL6_name4
		form3.text = CL6_form3
		form4.text = CL6_form4
		reason.text = CL6_reason
		
	if important_vars.current_pod == "CL7":
		name1.text = CL7_name1
		name2.text = CL7_name2
		form1.text = CL7_form1
		form2.text = CL7_form2
		name3.text = CL7_name3
		name4.text = CL7_name4
		form3.text = CL7_form3
		form4.text = CL7_form4
		reason.text = CL7_reason
		
	if important_vars.current_pod == "CL8":
		name1.text = CL8_name1
		name2.text = CL8_name2
		form1.text = CL8_form1
		form2.text = CL8_form2
		name3.text = CL8_name3
		name4.text = CL8_name4
		form3.text = CL8_form3
		form4.text = CL8_form4
		reason.text = CL8_reason

# D

	if important_vars.current_pod == "DL1":
		name1.text = DL1_name1
		name2.text = DL1_name2
		form1.text = DL1_form1
		form2.text = DL1_form2
		name3.text = DL1_name3
		name4.text = DL1_name4
		form3.text = DL1_form3
		form4.text = DL1_form4
		reason.text = DL1_reason

	if important_vars.current_pod == "DL2":
		name1.text = DL2_name1
		name2.text = DL2_name2
		form1.text = DL2_form1
		form2.text = DL2_form2
		name3.text = DL2_name3
		name4.text = DL2_name4
		form3.text = DL2_form3
		form4.text = DL2_form4
		reason.text = DL2_reason

	if important_vars.current_pod == "DL3":
		name1.text = DL3_name1
		name2.text = DL3_name2
		form1.text = DL3_form1
		form2.text = DL3_form2
		name3.text = DL3_name3
		name4.text = DL3_name4
		form3.text = DL3_form3
		form4.text = DL3_form4
		reason.text = DL3_reason

	if important_vars.current_pod == "DL4":
		name1.text = DL4_name1
		name2.text = DL4_name2
		form1.text = DL4_form1
		form2.text = DL4_form2
		name3.text = DL4_name3
		name4.text = DL4_name4
		form3.text = DL4_form3
		form4.text = DL4_form4
		reason.text = DL4_reason

	if important_vars.current_pod == "DL5":
		name1.text = DL5_name1
		name2.text = DL5_name2
		form1.text = DL5_form1
		form2.text = DL5_form2
		name3.text = DL5_name3
		name4.text = DL5_name4
		form3.text = DL5_form3
		form4.text = DL5_form4
		reason.text = DL5_reason

	if important_vars.current_pod == "DL6":
		name1.text = DL6_name1
		name2.text = DL6_name2
		form1.text = DL6_form1
		form2.text = DL6_form2
		name3.text = DL6_name3
		name4.text = DL6_name4
		form3.text = DL6_form3
		form4.text = DL6_form4
		reason.text = DL6_reason
		
	if important_vars.current_pod == "DL7":
		name1.text = DL7_name1
		name2.text = DL7_name2
		form1.text = DL7_form1
		form2.text = DL7_form2
		name3.text = DL7_name3
		name4.text = DL7_name4
		form3.text = DL7_form3
		form4.text = DL7_form4
		reason.text = DL7_reason
		
	if important_vars.current_pod == "DL8":
		name1.text = DL8_name1
		name2.text = DL8_name2
		form1.text = DL8_form1
		form2.text = DL8_form2
		name3.text = DL8_name3
		name4.text = DL8_name4
		form3.text = DL8_form3
		form4.text = DL8_form4
		reason.text = DL8_reason

# E

	if important_vars.current_pod == "EL1":
		name1.text = EL1_name1
		name2.text = EL1_name2
		form1.text = EL1_form1
		form2.text = EL1_form2
		name3.text = EL1_name3
		name4.text = EL1_name4
		form3.text = EL1_form3
		form4.text = EL1_form4
		reason.text = EL1_reason

	if important_vars.current_pod == "EL2":
		name1.text = EL2_name1
		name2.text = EL2_name2
		form1.text = EL2_form1
		form2.text = EL2_form2
		name3.text = EL2_name3
		name4.text = EL2_name4
		form3.text = EL2_form3
		form4.text = EL2_form4
		reason.text = EL2_reason

	if important_vars.current_pod == "EL3":
		name1.text = EL3_name1
		name2.text = EL3_name2
		form1.text = EL3_form1
		form2.text = EL3_form2
		name3.text = EL3_name3
		name4.text = EL3_name4
		form3.text = EL3_form3
		form4.text = EL3_form4
		reason.text = EL3_reason

	if important_vars.current_pod == "EL4":
		name1.text = EL4_name1
		name2.text = EL4_name2
		form1.text = EL4_form1
		form2.text = EL4_form2
		name3.text = EL4_name3
		name4.text = EL4_name4
		form3.text = EL4_form3
		form4.text = EL4_form4
		reason.text = EL4_reason

	if important_vars.current_pod == "EL5":
		name1.text = EL5_name1
		name2.text = EL5_name2
		form1.text = EL5_form1
		form2.text = EL5_form2
		name3.text = EL5_name3
		name4.text = EL5_name4
		form3.text = EL5_form3
		form4.text = EL5_form4
		reason.text = EL5_reason

	if important_vars.current_pod == "EL6":
		name1.text = EL6_name1
		name2.text = EL6_name2
		form1.text = EL6_form1
		form2.text = EL6_form2
		name3.text = EL6_name3
		name4.text = EL6_name4
		form3.text = EL6_form3
		form4.text = EL6_form4
		reason.text = EL6_reason
		
	if important_vars.current_pod == "EL7":
		name1.text = EL7_name1
		name2.text = EL7_name2
		form1.text = EL7_form1
		form2.text = EL7_form2
		name3.text = EL7_name3
		name4.text = EL7_name4
		form3.text = EL7_form3
		form4.text = EL7_form4
		reason.text = EL7_reason
		
	if important_vars.current_pod == "EL8":
		name1.text = EL8_name1
		name2.text = EL8_name2
		form1.text = EL8_form1
		form2.text = EL8_form2
		name3.text = EL8_name3
		name4.text = EL8_name4
		form3.text = EL8_form3
		form4.text = EL8_form4
		reason.text = EL8_reason

# F

	if important_vars.current_pod == "FL1":
		name1.text = FL1_name1
		name2.text = FL1_name2
		form1.text = FL1_form1
		form2.text = FL1_form2
		name3.text = FL1_name3
		name4.text = FL1_name4
		form3.text = FL1_form3
		form4.text = FL1_form4
		reason.text = FL1_reason

	if important_vars.current_pod == "FL2":
		name1.text = FL2_name1
		name2.text = FL2_name2
		form1.text = FL2_form1
		form2.text = FL2_form2
		name3.text = FL2_name3
		name4.text = FL2_name4
		form3.text = FL2_form3
		form4.text = FL2_form4
		reason.text = FL2_reason

	if important_vars.current_pod == "FL3":
		name1.text = FL3_name1
		name2.text = FL3_name2
		form1.text = FL3_form1
		form2.text = FL3_form2
		name3.text = FL3_name3
		name4.text = FL3_name4
		form3.text = FL3_form3
		form4.text = FL3_form4
		reason.text = FL3_reason

	if important_vars.current_pod == "FL4":
		name1.text = FL4_name1
		name2.text = FL4_name2
		form1.text = FL4_form1
		form2.text = FL4_form2
		name3.text = FL4_name3
		name4.text = FL4_name4
		form3.text = FL4_form3
		form4.text = FL4_form4
		reason.text = FL4_reason

	if important_vars.current_pod == "FL5":
		name1.text = FL5_name1
		name2.text = FL5_name2
		form1.text = FL5_form1
		form2.text = FL5_form2
		name3.text = FL5_name3
		name4.text = FL5_name4
		form3.text = FL5_form3
		form4.text = FL5_form4
		reason.text = FL5_reason

	if important_vars.current_pod == "FL6":
		name1.text = FL6_name1
		name2.text = FL6_name2
		form1.text = FL6_form1
		form2.text = FL6_form2
		name3.text = FL6_name3
		name4.text = FL6_name4
		form3.text = FL6_form3
		form4.text = FL6_form4
		reason.text = FL6_reason
		
	if important_vars.current_pod == "FL7":
		name1.text = FL7_name1
		name2.text = FL7_name2
		form1.text = FL7_form1
		form2.text = FL7_form2
		name3.text = FL7_name3
		name4.text = FL7_name4
		form3.text = FL7_form3
		form4.text = FL7_form4
		reason.text = FL7_reason
		
	if important_vars.current_pod == "FL8":
		name1.text = FL8_name1
		name2.text = FL8_name2
		form1.text = FL8_form1
		form2.text = FL8_form2
		name3.text = FL8_name3
		name4.text = FL8_name4
		form3.text = FL8_form3
		form4.text = FL8_form4
		reason.text = FL8_reason

# G

	if important_vars.current_pod == "GL1":
		name1.text = GL1_name1
		name2.text = GL1_name2
		form1.text = GL1_form1
		form2.text = GL1_form2
		name3.text = GL1_name3
		name4.text = GL1_name4
		form3.text = GL1_form3
		form4.text = GL1_form4
		reason.text = GL1_reason

	if important_vars.current_pod == "GL2":
		name1.text = GL2_name1
		name2.text = GL2_name2
		form1.text = GL2_form1
		form2.text = GL2_form2
		name3.text = GL2_name3
		name4.text = GL2_name4
		form3.text = GL2_form3
		form4.text = GL2_form4
		reason.text = GL2_reason

	if important_vars.current_pod == "GL3":
		name1.text = GL3_name1
		name2.text = GL3_name2
		form1.text = GL3_form1
		form2.text = GL3_form2
		name3.text = GL3_name3
		name4.text = GL3_name4
		form3.text = GL3_form3
		form4.text = GL3_form4
		reason.text = GL3_reason

	if important_vars.current_pod == "GL4":
		name1.text = GL4_name1
		name2.text = GL4_name2
		form1.text = GL4_form1
		form2.text = GL4_form2
		name3.text = GL4_name3
		name4.text = GL4_name4
		form3.text = GL4_form3
		form4.text = GL4_form4
		reason.text = GL4_reason

	if important_vars.current_pod == "GL5":
		name1.text = GL5_name1
		name2.text = GL5_name2
		form1.text = GL5_form1
		form2.text = GL5_form2
		name3.text = GL5_name3
		name4.text = GL5_name4
		form3.text = GL5_form3
		form4.text = GL5_form4
		reason.text = GL5_reason

	if important_vars.current_pod == "GL6":
		name1.text = GL6_name1
		name2.text = GL6_name2
		form1.text = GL6_form1
		form2.text = GL6_form2
		name3.text = GL6_name3
		name4.text = GL6_name4
		form3.text = GL6_form3
		form4.text = GL6_form4
		reason.text = GL6_reason
		
	if important_vars.current_pod == "GL7":
		name1.text = GL7_name1
		name2.text = GL7_name2
		form1.text = GL7_form1
		form2.text = GL7_form2
		name3.text = GL7_name3
		name4.text = GL7_name4
		form3.text = GL7_form3
		form4.text = GL7_form4
		reason.text = GL7_reason
		
	if important_vars.current_pod == "GL8":
		name1.text = GL8_name1
		name2.text = GL8_name2
		form1.text = GL8_form1
		form2.text = GL8_form2
		name3.text = GL8_name3
		name4.text = GL8_name4
		form3.text = GL8_form3
		form4.text = GL8_form4
		reason.text = GL8_reason

func set_values():
	if important_vars.current_pod == "A1L1":
		A1L1_name1 = name1.text
		A1L1_name2 = name2.text
		A1L1_form1 = form1.text
		A1L1_form2 = form2.text
		A1L1_reason = reason.text

	if important_vars.current_pod == "A1L2":
		A1L2_name1 = name1.text
		A1L2_name2 = name2.text
		A1L2_form1 = form1.text
		A1L2_form2 = form2.text
		A1L2_reason = reason.text

	if important_vars.current_pod == "A1L3":
		A1L3_name1 = name1.text
		A1L3_name2 = name2.text
		A1L3_form1 = form1.text
		A1L3_form2 = form2.text
		A1L3_reason = reason.text

	if important_vars.current_pod == "A1L4":
		A1L4_name1 = name1.text
		A1L4_name2 = name2.text
		A1L4_form1 = form1.text
		A1L4_form2 = form2.text
		A1L4_reason = reason.text

	if important_vars.current_pod == "A1L5":
		A1L5_name1 = name1.text
		A1L5_name2 = name2.text
		A1L5_form1 = form1.text
		A1L5_form2 = form2.text
		A1L5_reason = reason.text

	if important_vars.current_pod == "A1L6":
		A1L6_name1 = name1.text
		A1L6_name2 = name2.text
		A1L6_form1 = form1.text
		A1L6_form2 = form2.text
		A1L6_reason = reason.text

	if important_vars.current_pod == "A1L7":
		A1L7_name1 = name1.text
		A1L7_name2 = name2.text
		A1L7_form1 = form1.text
		A1L7_form2 = form2.text
		A1L7_reason = reason.text

	if important_vars.current_pod == "A1L8":
		A1L8_name1 = name1.text
		A1L8_name2 = name2.text
		A1L8_form1 = form1.text
		A1L8_form2 = form2.text
		A1L8_reason = reason.text

# A2

	if important_vars.current_pod == "A2L1":
		A2L1_name1 = name1.text
		A2L1_name2 = name2.text
		A2L1_form1 = form1.text
		A2L1_form2 = form2.text
		A2L1_reason = reason.text

	if important_vars.current_pod == "A2L2":
		A2L2_name1 = name1.text
		A2L2_name2 = name2.text
		A2L2_form1 = form1.text
		A2L2_form2 = form2.text
		A2L2_reason = reason.text

	if important_vars.current_pod == "A2L3":
		A2L3_name1 = name1.text
		A2L3_name2 = name2.text
		A2L3_form1 = form1.text
		A2L3_form2 = form2.text
		A2L3_reason = reason.text

	if important_vars.current_pod == "A2L4":
		A2L4_name1 = name1.text
		A2L4_name2 = name2.text
		A2L4_form1 = form1.text
		A2L4_form2 = form2.text
		A2L4_reason = reason.text

	if important_vars.current_pod == "A2L5":
		A2L5_name1 = name1.text
		A2L5_name2 = name2.text
		A2L5_form1 = form1.text
		A2L5_form2 = form2.text
		A2L5_reason = reason.text

	if important_vars.current_pod == "A2L6":
		A2L6_name1 = name1.text
		A2L6_name2 = name2.text
		A2L6_form1 = form1.text
		A2L6_form2 = form2.text
		A2L6_reason = reason.text

	if important_vars.current_pod == "A2L7":
		A2L7_name1 = name1.text
		A2L7_name2 = name2.text
		A2L7_form1 = form1.text
		A2L7_form2 = form2.text
		A2L7_reason = reason.text

	if important_vars.current_pod == "A2L8":
		A2L8_name1 = name1.text
		A2L8_name2 = name2.text
		A2L8_form1 = form1.text
		A2L8_form2 = form2.text
		A2L8_reason = reason.text

	if important_vars.current_pod == "B1L1":
		B1L1_name1 = name1.text
		B1L1_name2 = name2.text
		B1L1_form1 = form1.text
		B1L1_form2 = form2.text
		B1L1_reason = reason.text

	if important_vars.current_pod == "B1L2":
		B1L2_name1 = name1.text
		B1L2_name2 = name2.text
		B1L2_form1 = form1.text
		B1L2_form2 = form2.text
		B1L2_reason = reason.text

	if important_vars.current_pod == "B1L3":
		B1L3_name1 = name1.text
		B1L3_name2 = name2.text
		B1L3_form1 = form1.text
		B1L3_form2 = form2.text
		B1L3_reason = reason.text

	if important_vars.current_pod == "B1L4":
		B1L4_name1 = name1.text
		B1L4_name2 = name2.text
		B1L4_form1 = form1.text
		B1L4_form2 = form2.text
		B1L4_reason = reason.text

	if important_vars.current_pod == "B1L5":
		B1L5_name1 = name1.text
		B1L5_name2 = name2.text
		B1L5_form1 = form1.text
		B1L5_form2 = form2.text
		B1L5_reason = reason.text

	if important_vars.current_pod == "B1L6":
		B1L6_name1 = name1.text
		B1L6_name2 = name2.text
		B1L6_form1 = form1.text
		B1L6_form2 = form2.text
		B1L6_reason = reason.text

	if important_vars.current_pod == "B1L7":
		B1L7_name1 = name1.text
		B1L7_name2 = name2.text
		B1L7_form1 = form1.text
		B1L7_form2 = form2.text
		B1L7_reason = reason.text

	if important_vars.current_pod == "B1L8":
		B1L8_name1 = name1.text
		B1L8_name2 = name2.text
		B1L8_form1 = form1.text
		B1L8_form2 = form2.text
		B1L8_reason = reason.text

# B2

	if important_vars.current_pod == "B2L1":
		B2L1_name1 = name1.text
		B2L1_name2 = name2.text
		B2L1_form1 = form1.text
		B2L1_form2 = form2.text
		B2L1_reason = reason.text

	if important_vars.current_pod == "B2L2":
		B2L2_name1 = name1.text
		B2L2_name2 = name2.text
		B2L2_form1 = form1.text
		B2L2_form2 = form2.text
		B2L2_reason = reason.text

	if important_vars.current_pod == "B2L3":
		B2L3_name1 = name1.text
		B2L3_name2 = name2.text
		B2L3_form1 = form1.text
		B2L3_form2 = form2.text
		B2L3_reason = reason.text

	if important_vars.current_pod == "B2L4":
		B2L4_name1 = name1.text
		B2L4_name2 = name2.text
		B2L4_form1 = form1.text
		B2L4_form2 = form2.text
		B2L4_reason = reason.text

	if important_vars.current_pod == "B2L5":
		B2L5_name1 = name1.text
		B2L5_name2 = name2.text
		B2L5_form1 = form1.text
		B2L5_form2 = form2.text
		B2L5_reason = reason.text

	if important_vars.current_pod == "B2L6":
		B2L6_name1 = name1.text
		B2L6_name2 = name2.text
		B2L6_form1 = form1.text
		B2L6_form2 = form2.text
		B2L6_reason = reason.text

	if important_vars.current_pod == "B2L7":
		B2L7_name1 = name1.text
		B2L7_name2 = name2.text
		B2L7_form1 = form1.text
		B2L7_form2 = form2.text
		B2L7_reason = reason.text

	if important_vars.current_pod == "B2L8":
		B2L8_name1 = name1.text
		B2L8_name2 = name2.text
		B2L8_form1 = form1.text
		B2L8_form2 = form2.text
		B2L8_reason = reason.text

# C

	if important_vars.current_pod == "CL1":
		CL1_name1 = name1.text
		CL1_name2 = name2.text
		CL1_form1 = form1.text
		CL1_form2 = form2.text
		CL1_name3 = name3.text
		CL1_name4 = name4.text
		CL1_form3 = form3.text
		CL1_form4 = form4.text
		CL1_reason = reason.text

	if important_vars.current_pod == "CL2":
		CL2_name1 = name1.text
		CL2_name2 = name2.text
		CL2_form1 = form1.text
		CL2_form2 = form2.text
		CL2_name3 = name3.text
		CL2_name4 = name4.text
		CL2_form3 = form3.text
		CL2_form4 = form4.text
		CL2_reason = reason.text

	if important_vars.current_pod == "CL3":
		CL3_name1 = name1.text
		CL3_name2 = name2.text
		CL3_form1 = form1.text
		CL3_form2 = form2.text
		CL3_name3 = name3.text
		CL3_name4 = name4.text
		CL3_form3 = form3.text
		CL3_form4 = form4.text
		CL3_reason = reason.text

	if important_vars.current_pod == "CL4":
		CL4_name1 = name1.text
		CL4_name2 = name2.text
		CL4_form1 = form1.text
		CL4_form2 = form2.text
		CL4_name3 = name3.text
		CL4_name4 = name4.text
		CL4_form3 = form3.text
		CL4_form4 = form4.text
		CL4_reason = reason.text

	if important_vars.current_pod == "CL5":
		CL5_name1 = name1.text
		CL5_name2 = name2.text
		CL5_form1 = form1.text
		CL5_form2 = form2.text
		CL5_name3 = name3.text
		CL5_name4 = name4.text
		CL5_form3 = form3.text
		CL5_form4 = form4.text
		CL5_reason = reason.text

	if important_vars.current_pod == "CL6":
		CL6_name1 = name1.text
		CL6_name2 = name2.text
		CL6_form1 = form1.text
		CL6_form2 = form2.text
		CL6_name3 = name3.text
		CL6_name4 = name4.text
		CL6_form3 = form3.text
		CL6_form4 = form4.text
		CL6_reason = reason.text

	if important_vars.current_pod == "CL7":
		CL7_name1 = name1.text
		CL7_name2 = name2.text
		CL7_form1 = form1.text
		CL7_form2 = form2.text
		CL7_name3 = name3.text
		CL7_name4 = name4.text
		CL7_form3 = form3.text
		CL7_form4 = form4.text
		CL7_reason = reason.text

	if important_vars.current_pod == "CL8":
		CL8_name1 = name1.text
		CL8_name2 = name2.text
		CL8_form1 = form1.text
		CL8_form2 = form2.text
		CL8_name3 = name3.text
		CL8_name4 = name4.text
		CL8_form3 = form3.text
		CL8_form4 = form4.text
		CL8_reason = reason.text

# D

	if important_vars.current_pod == "DL1":
		DL1_name1 = name1.text
		DL1_name2 = name2.text
		DL1_form1 = form1.text
		DL1_form2 = form2.text
		DL1_name3 = name3.text
		DL1_name4 = name4.text
		DL1_form3 = form3.text
		DL1_form4 = form4.text
		DL1_reason = reason.text

	if important_vars.current_pod == "DL2":
		DL2_name1 = name1.text
		DL2_name2 = name2.text
		DL2_form1 = form1.text
		DL2_form2 = form2.text
		DL2_name3 = name3.text
		DL2_name4 = name4.text
		DL2_form3 = form3.text
		DL2_form4 = form4.text
		DL2_reason = reason.text

	if important_vars.current_pod == "DL3":
		DL3_name1 = name1.text
		DL3_name2 = name2.text
		DL3_form1 = form1.text
		DL3_form2 = form2.text
		DL3_name3 = name3.text
		DL3_name4 = name4.text
		DL3_form3 = form3.text
		DL3_form4 = form4.text
		DL3_reason = reason.text

	if important_vars.current_pod == "DL4":
		DL4_name1 = name1.text
		DL4_name2 = name2.text
		DL4_form1 = form1.text
		DL4_form2 = form2.text
		DL4_name3 = name3.text
		DL4_name4 = name4.text
		DL4_form3 = form3.text
		DL4_form4 = form4.text
		DL4_reason = reason.text

	if important_vars.current_pod == "DL5":
		DL5_name1 = name1.text
		DL5_name2 = name2.text
		DL5_form1 = form1.text
		DL5_form2 = form2.text
		DL5_name3 = name3.text
		DL5_name4 = name4.text
		DL5_form3 = form3.text
		DL5_form4 = form4.text
		DL5_reason = reason.text

	if important_vars.current_pod == "DL6":
		DL6_name1 = name1.text
		DL6_name2 = name2.text
		DL6_form1 = form1.text
		DL6_form2 = form2.text
		DL6_name3 = name3.text
		DL6_name4 = name4.text
		DL6_form3 = form3.text
		DL6_form4 = form4.text
		DL6_reason = reason.text

	if important_vars.current_pod == "DL7":
		DL7_name1 = name1.text
		DL7_name2 = name2.text
		DL7_form1 = form1.text
		DL7_form2 = form2.text
		DL7_name3 = name3.text
		DL7_name4 = name4.text
		DL7_form3 = form3.text
		DL7_form4 = form4.text
		DL7_reason = reason.text

	if important_vars.current_pod == "DL8":
		DL8_name1 = name1.text
		DL8_name2 = name2.text
		DL8_form1 = form1.text
		DL8_form2 = form2.text
		DL8_name3 = name3.text
		DL8_name4 = name4.text
		DL8_form3 = form3.text
		DL8_form4 = form4.text
		DL8_reason = reason.text
		
# E

	if important_vars.current_pod == "EL1":
		EL1_name1 = name1.text
		EL1_name2 = name2.text
		EL1_form1 = form1.text
		EL1_form2 = form2.text
		EL1_name3 = name3.text
		EL1_name4 = name4.text
		EL1_form3 = form3.text
		EL1_form4 = form4.text
		EL1_reason = reason.text

	if important_vars.current_pod == "EL2":
		EL2_name1 = name1.text
		EL2_name2 = name2.text
		EL2_form1 = form1.text
		EL2_form2 = form2.text
		EL2_name3 = name3.text
		EL2_name4 = name4.text
		EL2_form3 = form3.text
		EL2_form4 = form4.text
		EL2_reason = reason.text

	if important_vars.current_pod == "EL3":
		EL3_name1 = name1.text
		EL3_name2 = name2.text
		EL3_form1 = form1.text
		EL3_form2 = form2.text
		EL3_name3 = name3.text
		EL3_name4 = name4.text
		EL3_form3 = form3.text
		EL3_form4 = form4.text
		EL3_reason = reason.text

	if important_vars.current_pod == "EL4":
		EL4_name1 = name1.text
		EL4_name2 = name2.text
		EL4_form1 = form1.text
		EL4_form2 = form2.text
		EL4_name3 = name3.text
		EL4_name4 = name4.text
		EL4_form3 = form3.text
		EL4_form4 = form4.text
		EL4_reason = reason.text

	if important_vars.current_pod == "EL5":
		EL5_name1 = name1.text
		EL5_name2 = name2.text
		EL5_form1 = form1.text
		EL5_form2 = form2.text
		EL5_name3 = name3.text
		EL5_name4 = name4.text
		EL5_form3 = form3.text
		EL5_form4 = form4.text
		EL5_reason = reason.text

	if important_vars.current_pod == "EL6":
		EL6_name1 = name1.text
		EL6_name2 = name2.text
		EL6_form1 = form1.text
		EL6_form2 = form2.text
		EL6_name3 = name3.text
		EL6_name4 = name4.text
		EL6_form3 = form3.text
		EL6_form4 = form4.text
		EL6_reason = reason.text

	if important_vars.current_pod == "EL7":
		EL7_name1 = name1.text
		EL7_name2 = name2.text
		EL7_form1 = form1.text
		EL7_form2 = form2.text
		EL7_name3 = name3.text
		EL7_name4 = name4.text
		EL7_form3 = form3.text
		EL7_form4 = form4.text
		EL7_reason = reason.text

	if important_vars.current_pod == "EL8":
		EL8_name1 = name1.text
		EL8_name2 = name2.text
		EL8_form1 = form1.text
		EL8_form2 = form2.text
		EL8_name3 = name3.text
		EL8_name4 = name4.text
		EL8_form3 = form3.text
		EL8_form4 = form4.text
		EL8_reason = reason.text

# F

	if important_vars.current_pod == "FL1":
		FL1_name1 = name1.text
		FL1_name2 = name2.text
		FL1_form1 = form1.text
		FL1_form2 = form2.text
		FL1_name3 = name3.text
		FL1_name4 = name4.text
		FL1_form3 = form3.text
		FL1_form4 = form4.text
		FL1_reason = reason.text

	if important_vars.current_pod == "FL2":
		FL2_name1 = name1.text
		FL2_name2 = name2.text
		FL2_form1 = form1.text
		FL2_form2 = form2.text
		FL2_name3 = name3.text
		FL2_name4 = name4.text
		FL2_form3 = form3.text
		FL2_form4 = form4.text
		FL2_reason = reason.text

	if important_vars.current_pod == "FL3":
		FL3_name1 = name1.text
		FL3_name2 = name2.text
		FL3_form1 = form1.text
		FL3_form2 = form2.text
		FL3_name3 = name3.text
		FL3_name4 = name4.text
		FL3_form3 = form3.text
		FL3_form4 = form4.text
		FL3_reason = reason.text

	if important_vars.current_pod == "FL4":
		FL4_name1 = name1.text
		FL4_name2 = name2.text
		FL4_form1 = form1.text
		FL4_form2 = form2.text
		FL4_name3 = name3.text
		FL4_name4 = name4.text
		FL4_form3 = form3.text
		FL4_form4 = form4.text
		FL4_reason = reason.text

	if important_vars.current_pod == "FL5":
		FL5_name1 = name1.text
		FL5_name2 = name2.text
		FL5_form1 = form1.text
		FL5_form2 = form2.text
		FL5_name3 = name3.text
		FL5_name4 = name4.text
		FL5_form3 = form3.text
		FL5_form4 = form4.text
		FL5_reason = reason.text

	if important_vars.current_pod == "FL6":
		FL6_name1 = name1.text
		FL6_name2 = name2.text
		FL6_form1 = form1.text
		FL6_form2 = form2.text
		FL6_name3 = name3.text
		FL6_name4 = name4.text
		FL6_form3 = form3.text
		FL6_form4 = form4.text
		FL6_reason = reason.text

	if important_vars.current_pod == "FL7":
		FL7_name1 = name1.text
		FL7_name2 = name2.text
		FL7_form1 = form1.text
		FL7_form2 = form2.text
		FL7_name3 = name3.text
		FL7_name4 = name4.text
		FL7_form3 = form3.text
		FL7_form4 = form4.text
		FL7_reason = reason.text

	if important_vars.current_pod == "FL8":
		FL8_name1 = name1.text
		FL8_name2 = name2.text
		FL8_form1 = form1.text
		FL8_form2 = form2.text
		FL8_name3 = name3.text
		FL8_name4 = name4.text
		FL8_form3 = form3.text
		FL8_form4 = form4.text
		FL8_reason = reason.text

# G

	if important_vars.current_pod == "GL1":
		GL1_name1 = name1.text
		GL1_name2 = name2.text
		GL1_form1 = form1.text
		GL1_form2 = form2.text
		GL1_name3 = name3.text
		GL1_name4 = name4.text
		GL1_form3 = form3.text
		GL1_form4 = form4.text
		GL1_reason = reason.text

	if important_vars.current_pod == "GL2":
		GL2_name1 = name1.text
		GL2_name2 = name2.text
		GL2_form1 = form1.text
		GL2_form2 = form2.text
		GL2_name3 = name3.text
		GL2_name4 = name4.text
		GL2_form3 = form3.text
		GL2_form4 = form4.text
		GL2_reason = reason.text

	if important_vars.current_pod == "GL3":
		GL3_name1 = name1.text
		GL3_name2 = name2.text
		GL3_form1 = form1.text
		GL3_form2 = form2.text
		GL3_name3 = name3.text
		GL3_name4 = name4.text
		GL3_form3 = form3.text
		GL3_form4 = form4.text
		GL3_reason = reason.text

	if important_vars.current_pod == "GL4":
		GL4_name1 = name1.text
		GL4_name2 = name2.text
		GL4_form1 = form1.text
		GL4_form2 = form2.text
		GL4_name3 = name3.text
		GL4_name4 = name4.text
		GL4_form3 = form3.text
		GL4_form4 = form4.text
		GL4_reason = reason.text

	if important_vars.current_pod == "GL5":
		GL5_name1 = name1.text
		GL5_name2 = name2.text
		GL5_form1 = form1.text
		GL5_form2 = form2.text
		GL5_name3 = name3.text
		GL5_name4 = name4.text
		GL5_form3 = form3.text
		GL5_form4 = form4.text
		GL5_reason = reason.text

	if important_vars.current_pod == "GL6":
		GL6_name1 = name1.text
		GL6_name2 = name2.text
		GL6_form1 = form1.text
		GL6_form2 = form2.text
		GL6_name3 = name3.text
		GL6_name4 = name4.text
		GL6_form3 = form3.text
		GL6_form4 = form4.text
		GL6_reason = reason.text

	if important_vars.current_pod == "GL7":
		GL7_name1 = name1.text
		GL7_name2 = name2.text
		GL7_form1 = form1.text
		GL7_form2 = form2.text
		GL7_name3 = name3.text
		GL7_name4 = name4.text
		GL7_form3 = form3.text
		GL7_form4 = form4.text
		GL7_reason = reason.text

	if important_vars.current_pod == "GL8":
		GL8_name1 = name1.text
		GL8_name2 = name2.text
		GL8_form1 = form1.text
		GL8_form2 = form2.text
		GL8_name3 = name3.text
		GL8_name4 = name4.text
		GL8_form3 = form3.text
		GL8_form4 = form4.text
		GL8_reason = reason.text
